#开发环境
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1172597631
    hikari:
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DatebookHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      max-lifetime: 28740000
      connection-test-query: SELECT 1
  redis:
      database: 6  #Redis索引0~15，默认为0
      host: 127.0.0.1
      port: 6379
      password:  #密码（默认为空）
      lettuce: # 这里标明使用lettuce配置
        pool:
          max-active: 8   #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 5     #连接池中的最大空闲连接
          min-idle: 0     #连接池中的最小空闲连接
      timeout: 10000ms    #连接超时时间（毫秒）
logging:
  level:
    root: info
    com.zx: debug
  file:
    path: log/blog-dev

# mybatis config
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zx.blog.entity




